apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: collaboration-service
  name: collaboration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
      - image: nimbleplatform/collaboration-service:IMAGE_TAG
        imagePullPolicy: Always
        name: collaboration-service
        env:
        - name: MESSAGE_HUB_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: messagehub-credentials
              key: credentials.json
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
